install.packages("ggplot2")
install.packages("geometry")
library(ggplot2)
library(Rcpp)
library(volesti)
library(volesti)
library(geometry)

P <- GenCube(3,'H')
print(volume(P))
help("volume")
help("sample_points")

library(ggplot2)
library(volesti)